spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/restaurant_reserved}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:8834@Cvb}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:ht2HA7fTNBFLwpfAqeyVEKnnR0R5isKkaJCvW7eICSgDUoiGQKSbNmeVbPyGy2VrjrPI9HXD01sjTkslZv1qtlJrXBZQow475qx9c3LPbNTsVbECPeJfApbQxtWH1i5Tqzdvvdx1poXB5DhUg4Ducd4vvi5xCERzDj6xguahisW76ZJwe0lcW7U6NbliIeaCCvWhKO4LvAuiJFDKv0v77tWi32te9g6kdWSvbvAOQctcGUhnTPyZOusOhUe5T9Ks}
app.base-url=${APP_BASE_URL:http://localhost:8080}

spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

# MailHog
spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}